import {
  PrivateTransaction,
  ProjectDetails,
  HDBTransaction,
} from './types';

// ─── Private Property Transactions ────────────────────────────────

export const privateTransactions: PrivateTransaction[] = [
  // === Changi Heights (3 Jalan Sinar Bintang - freehold terrace) ===
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    propertyType: 'Terrace',
    tenure: 'Freehold',
    areaSqft: 1773,
    areaSqm: 164.7,
    price: 3730000,
    psf: 2104,
    psm: 22645,
    contractDate: 'Oct 2025',
    type: 'Terrace',
    marketSegment: 'RCR',
  },
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    propertyType: 'Terrace',
    tenure: 'Freehold',
    areaSqft: 1783,
    areaSqm: 165.6,
    price: 3660000,
    psf: 2052,
    psm: 22101,
    contractDate: 'Jun 2025',
    type: 'Terrace',
    marketSegment: 'RCR',
  },
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    propertyType: 'Terrace',
    tenure: 'Freehold',
    areaSqft: 2403,
    areaSqm: 223.2,
    price: 3860000,
    psf: 1607,
    psm: 17294,
    contractDate: 'Jun 2024',
    type: 'Terrace',
    marketSegment: 'RCR',
  },
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    propertyType: 'Terrace',
    tenure: 'Freehold',
    areaSqft: 1733,
    areaSqm: 161.0,
    price: 3400000,
    psf: 1962,
    psm: 21118,
    contractDate: 'May 2024',
    type: 'Terrace',
    marketSegment: 'RCR',
  },
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    propertyType: 'Terrace',
    tenure: 'Freehold',
    areaSqft: 2287,
    areaSqm: 212.5,
    price: 3859000,
    psf: 1687,
    psm: 18160,
    contractDate: 'Apr 2024',
    type: 'Terrace',
    marketSegment: 'RCR',
  },

  // === The Interlace (Condo, D4) ===
  {
    projectName: 'The Interlace',
    address: '180 Depot Road',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1615,
    areaSqm: 150.0,
    price: 3200000,
    psf: 1981,
    psm: 21333,
    contractDate: 'Mar 2024',
    type: 'Condo',
    marketSegment: 'RCR',
  },
  {
    projectName: 'The Interlace',
    address: '180 Depot Road',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1615,
    areaSqm: 150.0,
    price: 3000000,
    psf: 1857,
    psm: 20000,
    contractDate: 'Dec 2023',
    type: 'Condo',
    marketSegment: 'RCR',
  },
  {
    projectName: 'The Interlace',
    address: '180 Depot Road',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1550,
    areaSqm: 144.0,
    price: 2888000,
    psf: 1863,
    psm: 20056,
    contractDate: 'Aug 2023',
    type: 'Condo',
    marketSegment: 'RCR',
  },

  // === Marina One Residences (Condo, D1) ===
  {
    projectName: 'Marina One Residences',
    address: '5 Straits View',
    district: 1,
    districtName: 'Marina Bay / Raffles Place',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1292,
    areaSqm: 120.0,
    price: 2680000,
    psf: 2074,
    psm: 22333,
    contractDate: 'Feb 2024',
    type: 'Condo',
    marketSegment: 'CCR',
  },
  {
    projectName: 'Marina One Residences',
    address: '5 Straits View',
    district: 1,
    districtName: 'Marina Bay / Raffles Place',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1292,
    areaSqm: 120.0,
    price: 2500000,
    psf: 1935,
    psm: 20833,
    contractDate: 'Nov 2023',
    type: 'Condo',
    marketSegment: 'CCR',
  },

  // === Reflections at Keppel Bay (Condo, D4) ===
  {
    projectName: 'Reflections at Keppel Bay',
    address: '1 Keppel Bay View',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1884,
    areaSqm: 175.0,
    price: 3950000,
    psf: 2097,
    psm: 22571,
    contractDate: 'Jan 2024',
    type: 'Condo',
    marketSegment: 'RCR',
  },
  {
    projectName: 'Reflections at Keppel Bay',
    address: '1 Keppel Bay View',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 2153,
    areaSqm: 200.0,
    price: 4200000,
    psf: 1951,
    psm: 21000,
    contractDate: 'Oct 2023',
    type: 'Condo',
    marketSegment: 'RCR',
  },

  // === D'Leedon (Condo, D10) ===
  {
    projectName: "D'Leedon",
    address: '1 Leedon Heights',
    district: 10,
    districtName: 'Bukit Timah / Holland Road',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1249,
    areaSqm: 116.0,
    price: 2520000,
    psf: 2018,
    psm: 21724,
    contractDate: 'Feb 2024',
    type: 'Condo',
    marketSegment: 'CCR',
  },
  {
    projectName: "D'Leedon",
    address: '1 Leedon Heights',
    district: 10,
    districtName: 'Bukit Timah / Holland Road',
    propertyType: 'Condo',
    tenure: '99-year Leasehold',
    areaSqft: 1206,
    areaSqm: 112.0,
    price: 2350000,
    psf: 1949,
    psm: 20982,
    contractDate: 'Nov 2023',
    type: 'Condo',
    marketSegment: 'CCR',
  },
];

// ─── HDB Resale Transactions ──────────────────────────────────────

export const hdbTransactions: HDBTransaction[] = [
  // === 129 Kim Tian Road ===
  {
    block: '129',
    street: 'Kim Tian Road',
    town: 'Bukit Merah',
    flatType: '4-Room',
    floorRange: '04 to 06',
    floorAreaSqm: 88,
    leaseCommenceDate: 1974,
    remainingLease: '50 years',
    resalePrice: 545000,
    transactionDate: '2024-10',
    unitPricePsf: 575,
    unitPricePsm: 6193,
  },
  {
    block: '129',
    street: 'Kim Tian Road',
    town: 'Bukit Merah',
    flatType: '4-Room',
    floorRange: '01 to 03',
    floorAreaSqm: 88,
    leaseCommenceDate: 1974,
    remainingLease: '50 years',
    resalePrice: 555000,
    transactionDate: '2024-07',
    unitPricePsf: 586,
    unitPricePsm: 6307,
  },
  {
    block: '129',
    street: 'Kim Tian Road',
    town: 'Bukit Merah',
    flatType: '4-Room',
    floorRange: '01 to 03',
    floorAreaSqm: 88,
    leaseCommenceDate: 1974,
    remainingLease: '50 years',
    resalePrice: 510000,
    transactionDate: '2024-03',
    unitPricePsf: 538,
    unitPricePsm: 5795,
  },
  {
    block: '129',
    street: 'Kim Tian Road',
    town: 'Bukit Merah',
    flatType: '4-Room',
    floorRange: '10 to 12',
    floorAreaSqm: 88,
    leaseCommenceDate: 1974,
    remainingLease: '51 years',
    resalePrice: 548000,
    transactionDate: '2023-05',
    unitPricePsf: 579,
    unitPricePsm: 6227,
  },

  // === The Pinnacle @ Duxton ===
  {
    block: '1',
    street: 'Cantonment Road',
    town: 'Bukit Merah',
    flatType: '5-Room',
    floorRange: '40 to 42',
    floorAreaSqm: 110,
    leaseCommenceDate: 2004,
    remainingLease: '81 years',
    resalePrice: 1288000,
    transactionDate: '2024-03',
    unitPricePsf: 1087,
    unitPricePsm: 11709,
  },
  {
    block: '1',
    street: 'Cantonment Road',
    town: 'Bukit Merah',
    flatType: '5-Room',
    floorRange: '37 to 39',
    floorAreaSqm: 110,
    leaseCommenceDate: 2004,
    remainingLease: '81 years',
    resalePrice: 1250000,
    transactionDate: '2024-01',
    unitPricePsf: 1055,
    unitPricePsm: 11364,
  },
  {
    block: '1',
    street: 'Cantonment Road',
    town: 'Bukit Merah',
    flatType: '5-Room',
    floorRange: '34 to 36',
    floorAreaSqm: 108,
    leaseCommenceDate: 2004,
    remainingLease: '81 years',
    resalePrice: 1200000,
    transactionDate: '2023-11',
    unitPricePsf: 1032,
    unitPricePsm: 11111,
  },
];

// ─── Project Details ──────────────────────────────────────────────

export const projectDetails: ProjectDetails[] = [
  {
    projectName: 'Changi Heights',
    address: '3 Jalan Sinar Bintang',
    district: 16,
    districtName: 'Bedok / Upper East Coast',
    tenure: 'Freehold',
    totalUnits: 58,
    yearCompleted: 1996,
    propertyType: 'Terrace',
    marketSegment: 'RCR',
    description:
      'Changi Heights is an exclusive freehold terrace cluster nestled in the mature estate of Bedok. Quiet residential enclave with low density, offering spacious land area and proximity to Changi Business Park and Expo MRT.',
    amenities: ['Changi City Point', 'Expo MRT', 'Bedok Reservoir', 'East Coast Park', 'Changi Business Park'],
  },
  {
    projectName: 'The Interlace',
    address: '180 Depot Road',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    tenure: '99-year Leasehold',
    totalUnits: 1040,
    yearCompleted: 2013,
    propertyType: 'Condo',
    marketSegment: 'RCR',
    description:
      'The Interlace is an iconic, award-winning development by OMA / Ole Scheeren. Its distinctive hexagonal stacked design won World Building of the Year in 2015. Features extensive landscaping, multiple pools, and a resort-style lifestyle.',
    amenities: ['HarbourFront MRT', 'VivoCity', 'Sentosa', 'Mount Faber Park', 'Keppel Bay'],
  },
  {
    projectName: 'Marina One Residences',
    address: '5 Straits View',
    district: 1,
    districtName: 'Marina Bay / Raffles Place',
    tenure: '99-year Leasehold',
    totalUnits: 1042,
    yearCompleted: 2017,
    propertyType: 'Condo',
    marketSegment: 'CCR',
    description:
      'Marina One Residences is a luxury integrated development in Marina Bay financial district. Features a lush "Green Heart" garden at its core, direct access to Marina One MRT, and world-class amenities.',
    amenities: ['Marina Bay MRT', 'Marina One MRT', 'Marina Bay Financial Centre', 'Gardens by the Bay', 'The Shoppes at Marina Bay Sands'],
  },
  {
    projectName: 'Reflections at Keppel Bay',
    address: '1 Keppel Bay View',
    district: 4,
    districtName: 'Telok Blangah / HarbourFront',
    tenure: '99-year Leasehold',
    totalUnits: 1129,
    yearCompleted: 2012,
    propertyType: 'Condo',
    marketSegment: 'RCR',
    description:
      'Reflections at Keppel Bay is a stunning waterfront development designed by Daniel Libeskind. Its sculptural towers create a striking skyline along Keppel Bay with panoramic sea views and resort living.',
    amenities: ['HarbourFront MRT', 'Keppel Bay', 'VivoCity', 'Sentosa Cove', 'Mount Faber'],
  },
  {
    projectName: "D'Leedon",
    address: '1 Leedon Heights',
    district: 10,
    districtName: 'Bukit Timah / Holland Road',
    tenure: '99-year Leasehold',
    totalUnits: 1245,
    yearCompleted: 2014,
    propertyType: 'Condo',
    marketSegment: 'CCR',
    description:
      "D'Leedon is a prestigious freehold-equivalent development in coveted District 10. Designed by Zaha Hadid Architects, its seven sculptural towers sit amid lush landscaping with extensive facilities.",
    amenities: ['Botanic Gardens MRT', 'Farrer Road MRT', 'Dempsey Hill', 'Holland Village', 'Botanic Gardens'],
  },
];

// ─── Town / District Mapping ──────────────────────────────────────

export const singaporeTowns: string[] = [
  'Ang Mo Kio',
  'Bedok',
  'Bishan',
  'Bukit Batok',
  'Bukit Merah',
  'Bukit Panjang',
  'Bukit Timah',
  'Central Area',
  'Choa Chu Kang',
  'Clementi',
  'Geylang',
  'Hougang',
  'Jurong East',
  'Jurong West',
  'Kallang / Whampoa',
  'Marine Parade',
  'Pasir Ris',
  'Punggol',
  'Queenstown',
  'Sembawang',
  'Sengkang',
  'Serangoon',
  'Tampines',
  'Tanglin',
  'Tiong Bahru',
  'Toa Payoh',
  'Woodlands',
  'Yishun',
];

// ─── Helper ───────────────────────────────────────────────────────

export function getProjectByName(name: string): ProjectDetails | undefined {
  return projectDetails.find(
    (p) => p.projectName.toLowerCase() === name.toLowerCase()
  );
}

export function getPrivateTransactionsByName(
  name: string
): PrivateTransaction[] {
  return privateTransactions.filter(
    (t) => t.projectName.toLowerCase() === name.toLowerCase()
  );
}

export function getTransactionsByDistrict(district: number): PrivateTransaction[] {
  return privateTransactions.filter((t) => t.district === district);
}
